{% set name = "altgraph" %}
{% set version = "0.17.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c87b395dd12fabde9c99573a9749d67da8d29ef9de0125c7f536699b4a9bc9e7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - altgraph
    - altgraph.Graph
    - altgraph.GraphUtil
    - altgraph.ObjectGraph
  source_files:
    - altgraph_tests
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv --tb=short altgraph_tests
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/altgraph
  summary: Python graph (network) package
  description: |
      altgraph is a fork of graphlib: a graph (network)
      package for constructing graphs, BFS and DFS traversals,
      topological sort, shortest paths, etc. with graphviz output.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ronaldoussoren/altgraph
  doc_url: https://altgraph.readthedocs.io

extra:
  recipe-maintainers:
    - anthchirp
    - rth
