{% set name = "altgraph" %}
{% set version = "0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altgraph-{{ version }}.tar.gz
  sha256: 1f05a47122542f97028caf78775a095fbe6a2699b5089de8477eb583167d69aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - altgraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/altgraph/
  summary: Python graph (network) package
  description: |
      altgraph is a fork of graphlib: a graph (network)
      package for constructing graphs, BFS and DFS traversals,
      topological sort, shortest paths, etc. with graphviz output.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ronaldoussoren/altgraph/
  doc_url: https://altgraph.readthedocs.io

extra:
  recipe-maintainers:
    - anthchirp
    - rth
