travis:
  secure:
    BINSTAR_TOKEN: FZYlNI+YyOG3894tYM9riD38xpIQnYEgaGEy4h1dJdDrLsBfj/hHDyMp76bUsrdUQPqHeI4g/dJyV+ZcQ7ZKHzAGw0+7Tvi1tahiJhm0FGw/iFPdxiUy4nA1blETmoZ4h5WQGmqmKdqT2IGIHpo5pjSgx+H9XWd4UK4YwHIc7ThjpymHRNw9KOXkcp+oTNzofhyrYlZ65oEospkDUZXu8+Gb9ory/R6clNRp53GuK4MkCLiYBmeXv/K+OZm8A8NwKZu8a6ZWegnkPzM9BqxeAV3IYqcRtizDP/jZ33zuQvUgWcfa9jWe0olj6Bu6vVBCJFdBrI6wlOk99J6VugXDmXEci4H/Upb4zUneGaEa2MKcuuA7743+Nq9E83pqnFROqT9KgeYwuZpiE8D59wH0dMAMacQH+jiceV8sLNEiwi5o5jh2xzIbNdQCEacPP7FeYKjtvhRJh/L4YihmDjk36iqXG8zvKBFjHbeUqP55ja3X1/C/eKtJO5c80jN+LH1KjQ5M1NZBy1Ak2JvQcCnRKroBXC2tVuQANqb/xdG5Vl3FnA2V6doOjvWTlhjfANVFxJ9GrUFWc6c9fIAlRvqJ0m+bO8fOBfm9gQuxKTQ+8TIu15CSX+GLpqc0XWcU43vuGJO9DwNsS1q57oj2jJ/+fDPSf0TEbT6Rp9i6Uop4Nzw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
