travis:
  secure:
    BINSTAR_TOKEN: PZvWg5Swgai4H3iehGoN0hzMexKS3M8/7JHAYuL3exQWVYTfaTcpT9DkfRL5YCKqEqx5n57WvU1BsrUGPtnq4aJ9sxYV6bjyGbhkcHQkqaluVHxuf6BS4Wo9wcAgIckRYRQwMgR/GCl7bkei/Bsa9to2cFjRYBy/bte9LY2vBAQ5yRHopBpr3QLG+S59lCjNzzLjraCGQLj2BeVB7qz3jtzqeUNU40aPUwqMkmshhxbNgML65NMzyxpw5qpV+XPB1Eu7IeKw4TD4kVUUoI6oPAk/91El9y2OHM16LxX1FQY0OQf49GctD/xFX6m3ciPlEazAvk2J+RhfjRUeTYH3jqDbc3jdS3deFels36AHvMxD4gQQSiEmJE0sVaRxMNPUwd9Xte1GFZIO335S9xH3lJ+1hp0l3CEUaPMFpDLxMpISMLheplMSKxi7/l8kA1C2PiIhw7RPwyBJ06ncWQPg8IyDzsiTfhZMSaxJ4smkoIhlKVt8BfYn5+nmiHgWGQVtAnBh+jUFP8L9nqiMSxopN/PFjK3fb5zPHcmwrUvEgFkP5W9ZCvowAIpiEXi9BVzmMyVUOTfMPibMoLrt+/6q3VbOxb4jRsz0HnWkfQFy0XX0Dc3iSjFodE8IQtkePEqI17nZ3H/zu8E0JHD7YLSHactafmC5uixX0arXbgOHP48=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
